name: Dynmap-PreciousStones
main: net.sacredlabyrinth.phaed.dynmap.preciousstones.DynmapPreciousStones
version: 1.1
author: phaed
softdepend: [ dynmap, PreciousStones ]
commands:
  map:
    description: Map commands
    usage: Syntax error, verify the command usage and try again
permissions:
  preciousstones.map.toggle:
    description: Can toggle map visibility
